# Generated by Django 3.1.5 on 2021-01-22 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='Posição Operacional', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do Usuário', max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photos/')),
                ('created_au', models.DateTimeField(auto_now_add=True)),
                ('update_au', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=255)),
                ('rev', models.CharField(max_length=3)),
                ('comment', models.TextField()),
                ('created_tk', models.DateTimeField(auto_now_add=True)),
                ('update_tk', models.DateTimeField(auto_now=True)),
                ('elab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elab', to='task.appuser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.status')),
                ('verif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verif', to='task.appuser')),
            ],
        ),
    ]
